import Welcome from '@/components/Welcome';
import './globals.css';
import Sidebar from '@/components/Sidebar';

export const metadata = {
  title: 'Today | Next Todo',
  description: 'Generated by create next app',
};

export const savedTodos = [
  /* {id:timestamp,todos:array[]} */
  {
    id: 1683727246000,
    todos: [
      { id: 1683725950, content: '분리수거 하기' },
      { id: 1683725800, content: '빨래 하기' },
    ],
  },
  {
    id: 1683466770000,
    todos: [
      { id: 1683466700, content: '꽃 배달 주문하기' },
      { id: 1683466600, content: '블로깅 하기' },
    ],
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Welcome />
        <Sidebar savedTodos={savedTodos} />
        {children}
      </body>
    </html>
  );
}
