import Welcome from '@/components/Welcome';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import ReduxProvider from '@/redux/reduxProvider';

export const metadata = {
  title: 'Today | Next Todo',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <ReduxProvider>
          <Welcome />
          <Sidebar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
